### ISSUE TITLE
Why is MS-PL licence file included?

### ISSUE THREAD

**Issue by BorisUK** [ironyproject/irony#13]
The project contains two licence files:

MIT: https://github.com/IronyProject/Irony/blob/master/LICENSE
MS-PL: https://github.com/IronyProject/Irony/blob/master/Irony/MS-PubLicense.Rtf

Why is the MS-PL licence file included? Can it be removed to avoid any doubts as to which licence applies to this project?

Thanks

**Comment by yallie** [comment]
Good catch, thanks!
The license it MIT.
