### ISSUE TITLE
Consuming AST Trees

### ISSUE THREAD

**Issue by chuck-flowers** [ironyproject/irony#15]
Hey I've gotten kind of stuck here.

I'm in the process of using Irony to make a domain specific templating language. The grammar is really simple so I've already constructed my AST/ParseTree. Now I just need to resolve the AST to the output of the template. Are there any utilities that help with this included with Irony? I've searched throughout the solution and haven't really found anything to help. There doesn't seem to be much in the way of documentation so I'm really not sure where the best place to find what I'm looking for is.

Any help or redirection to useful resources is much appreciated.

**Comment by digitalbricklayer** [comment]
If I understand you question correctly I think you need the [interpreter](https://github.com/IronyProject/Irony/tree/master/Irony.Interpreter). Or roll your own interpreter as I did using the AST you've already built. Your interpreter will take your template and expand it appropriately. If any of these ideas are new to you, then I suggest that you are going to have a steep learning curve ahead of you. There isn't much here that is going to help you learn. If you want an example, I can suggest you have a look at [my project](https://github.com/digitalbricklayer/workbench) that uses Irony quite a lot in the core project under grammars.

**Comment by chuck-flowers** [comment]
Okay thanks. I understand the concept of an interpreter and I could resolve the tree myself without it if need be. I was just making sure there wasn't a tree traverser API similar to what Roslyn provides before I started to roll my own.

**Comment by digitalbricklayer** [comment]
There is a visitor API you can use to traverse the AST. Something like this:

                var sharedDomainExpressionNode = (SharedDomainExpressionNode) parseTree.Root.AstNode;
                var variableReferenceCaptureVisitor = new ConstraintVariableReferenceCaptureVisitor();
                sharedDomainExpressionNode.AcceptVisitor(variableReferenceCaptureVisitor);

The visitor looks a bit like this:

    /// <summary>
    /// Visitor to record information used when validating the constraint 
    /// expression from the abstract syntax tree.
    /// </summary>
    public class ConstraintVariableReferenceCaptureVisitor : IAstVisitor
    {
        private readonly List<SingletonVariableReferenceNode> singletonVariableReferences;
        private readonly List<AggregateVariableReferenceNode> aggregateVariableReferences;

        public ConstraintVariableReferenceCaptureVisitor()
        {
            this.singletonVariableReferences = new List<SingletonVariableReferenceNode>();
            this.aggregateVariableReferences = new List<AggregateVariableReferenceNode>();
        }

        public void BeginVisit(IVisitableNode node)
        {
            switch (node)
            {
                case AggregateVariableReferenceNode aggregateVariableReferenceNode:
                    this.aggregateVariableReferences.Add(aggregateVariableReferenceNode);
                    break;

                case SingletonVariableReferenceNode singletonVariableReferenceNode:
                    this.singletonVariableReferences.Add(singletonVariableReferenceNode);
                    break;
            }
        }

        public void EndVisit(IVisitableNode node)
        {
        }

        public VariableReferences GetReferences()
        {
            return new VariableReferences(this.singletonVariableReferences, this.aggregateVariableReferences);
        }

        public class VariableReferences
        {
            private readonly List<SingletonVariableReferenceNode> singletonVariableReferences;
            private readonly List<AggregateVariableReferenceNode> aggregateVariableReferences;

            public VariableReferences(IEnumerable<SingletonVariableReferenceNode> theSingletonReferences, IEnumerable<AggregateVariableReferenceNode> theAggregateReferences)
            {
                Contract.Requires<ArgumentNullException>(theSingletonReferences != null);
                Contract.Requires<ArgumentNullException>(theAggregateReferences != null);

                this.singletonVariableReferences = new List<SingletonVariableReferenceNode>(theSingletonReferences);
                this.aggregateVariableReferences = new List<AggregateVariableReferenceNode>(theAggregateReferences);
            }

            /// <summary>
            /// Gets all singleton variable references.
            /// </summary>
            public IReadOnlyCollection<SingletonVariableReferenceNode> SingletonVariableReferences => this.singletonVariableReferences;

            /// <summary>
            /// Gets all aggregate variable references.
            /// </summary>
            public IReadOnlyCollection<AggregateVariableReferenceNode> AggregateVariableReferences => this.aggregateVariableReferences;
        }
    }
