### ISSUE TITLE
GraphQL and other things

### ISSUE THREAD

**Issue by rivantsov** [ironyproject/irony#16]
Hi everybody!
Happy 2019! Irony turns 11 this year, what an age. 
First of all, big thanks to Alexey and other folks who took over the project and helped maintaining it, while I was out there doing other stuff... Really appreciate your efforts. 
Now, guess what... 2019 appears to be about GraphQL, all over the place. And it means Irony is back into spotlight. The world needs efficient parser, and Irony is here to help. Which means I'm actively back to Irony project. 
I've started a new project for all GraphQL things, have a look: 
https://github.com/rivantsov/ngraphql
for now,  contains only Irony-based full GraphQL grammar. You can try it with Grammar Explorer. Btw, having hard time finding sample GraphQL files - any tips? 
To my own surprise, it was quite painless to implement full GQL grammar, no troubles. 
More things planned - full blown GQL server, and integration with VITA as underlying ORM (as well as independent ORM-agnostic server). And Irony will be upgraded and enhanced for sure.   
Roman

**Comment by yallie** [comment]
Hi Roman,

that's awesome, glad to see you back! :)
Implementing GraphQL spec seems like a very ambitious project.

>Irony turns 11 this year, what an age.

Oh my, that's hard to believe!
