### ISSUE TITLE
Irony 1.1.0 has undeclared dependency on System.Net.Http 4.2.0

### ISSUE THREAD

**Issue by WenningQiu** [ironyproject/irony#19]
Although the package (Irony 1.1.0) shows no dependency, we found it pulls in System.Net.Http 4.2.0 in our applications. Is System.Net.Http required for performing Irony functionality? If it does it should be listed on the packages dependency.

**Comment by yallie** [comment]
Hello @WenningQiu,

Irony doesn't use System.Net.Http, so it's probably a netstandard2.0 dependency.
Irony's own dependencies are explicitly listed in the .Net4.0 assembly:

![image](https://user-images.githubusercontent.com/672878/53899577-92bb8b00-404b-11e9-84e9-0eefa7bfa29c.png)

**Comment by WenningQiu** [comment]
I agree Yallie. I am sorry this is a false alarm, System.Net.Http.dll was brought in by another package.
