### ISSUE TITLE
.Net Standard targetting

### ISSUE THREAD

**Issue by cleverguy25** [ironyproject/irony#2]
You left a comment that this was something you are considering or in the works.  Need help?

**Comment by cleverguy25** [comment]
Just a note, I was able to get Irony and Irony.Interpreter running with most tests (removed _newarch tests and heredocterminal tests as they seemed a work in progress.  I just had to remove the lines to reflection.emit stuff, and replace with Expressions.  The tests pass, was going to play with it more

**Comment by yallie** [comment]
Hi, that's great! Help is always appreciated :)
May I ask for a pull request?

**Comment by yallie** [comment]
>removed _newarch tests and heredocterminal tests as they seemed a work in progress.

I see, these tests are excluded in the unit test projects.

>I just had to remove the lines to reflection.emit stuff, and replace with Expressions

Looks like all these can be kept as is using [System.Reflection.Emit.Lightweight](https://www.nuget.org/packages/System.Reflection.Emit.Lightweight) package.
Thanks @legigor for his [Irony.netcore.csproj](https://github.com/YouScan/Irony/commit/d5efedf1a5f00c31a93f8c360c9665f0b9764274#diff-506ff3e98c2babd45ef5aef707470181R11) version.

>May I ask for a pull request?

Nevermind, just pushed the updated project files targeting .NET Standard 2.0 and .NET 4.x.

Regards, Alex.
