### ISSUE TITLE
Irony for RoundCube

### ISSUE THREAD

**Issue by SLAY3RYTB** [ironyproject/irony#38]
Hi, 5 days to install Irony to get working calendar and others plugins on Roundcube but its impossible, im have testing all possibility im don't understand how to work ... please create and news update version in list of download named RoundCube 1.4.9 with Irony to use all plugins (Kobal and Chwala).

PLEASE create an a Irony roundcube version to help me, im need that for my work.

Thanks for your help.

Cordialy,
SLAY3R

**Comment by rivantsov** [comment]
i am sorry but wtf? why are we responsible for RoundCube release working?

**Comment by SLAY3RYTB** [comment]
You are not responsible for the functioning of the RoundCube version my there are plugins that only work if you install RoundCube on Irony and despite 5 days of work impossible to find one resulting from this problem, I found a link de Irony with roundcube install my this one is 7 years old .. it is a personal clone of a people my I would like to know it you could offer you a compatible version and better explain at the level of the installation tutorial

An a better version of there : https://github.com/detrout/irony

Cordialy,
SLAY3R

**Comment by rivantsov** [comment]
well, maybe I am missing something, but it looks like you are confused. The link you provided - it is github repo Irony by some dev (Diane); but it is php or something else, not sure, and it has nothing to do with this Irony (which is .NET parser framework). Sorry it appears these 2 Irony projects are completely unrelated.
