### ISSUE TITLE
Irony project divergence

### ISSUE THREAD

**Issue by awelburn** [ironyproject/irony#4]
Pinging @daxnet @legigor @rafalFurman for your thoughts on this as well please?

It seems like you all have got Irony running on various modern .NET environments which is good, it would be great if the community can come together to produce an "official" version that works on .NET Standard / Core.

Related to #2 in this repo, there is https://github.com/daxnet/irony which is a working port to .NET Core. I guess it could be switched to support .Net Standard, probably with far less effort that the original port?

I think it would be beneficial for the community that uses Irony if we could merge these two repos together so everyone can benefit from the combined development effort to modernise Irony?

If I had to pick, I'd merge https://github.com/daxnet/irony into this repo as the commit history from Codeplex has been preserved and this is also where the codeplex site brings people to.

**Comment by yallie** [comment]
Hello @awelburn, that sounds great. I was going to merge a couple of pending pull requests from codeplex into this repo, update the dependencies, etc. and then to look into porting to .NET Standard. Good to see that someone has already done this port.

What about the grammar explorer? The parser and interpreter engines seem to have no problems with porting, but GrammarExplorer is a WinForms application and cannot be ported to .NET Core.

**Comment by yallie** [comment]
Just pushed my changes:

* Updated the library projects to .NET Standard 2.0
* Replaced third-party binaries with Nuget packages
* Merged an old pull request to GrammarExplorer (readline support)
* Added simple Appveyor integration

To my great surprise, the library didn't need any changes, all APIs are there, all tests pass.
Note that GrammarExplorer is still WinForms and isn't supported on .NET Core.
But the parser/interpreter should work on .NET Core platforms.

**Comment by igitur** [comment]
I support this suggestion. @daxnet what is your thoughts on this? If we can get your support, maybe we can release a later version under https://www.nuget.org/packages/Irony.NetCore/ ? 

Your blessing would be highly appreciated.

**Comment by wasabii** [comment]
Yo.

I did the original NuGet package a few years ago.

I'd recommend ya'll just take ownership of that. And do a single nuget package with artifacts for both framework and standard, if you need to.

@rivantsov is part of this new effort, right?

[EDIT]

Nevermind. Just noticed the other issue where he already gave ya'll control.
