### ISSUE TITLE
[question] About the use of MakePlusRule

### ISSUE THREAD

**Issue by fawdlstty** [ironyproject/irony#42]
example code:

```csharp
// ...
var _base_value = new NonTerminal ("base_value") { Rule = _int_val | _float_val };
var _expr = new NonTerminal ("expr");
var _value = new NonTerminal ("value") { Rule = _base_value | ("(" + _expr + ")") | _expr };
var _val_op2 = new NonTerminal ("val_op2") { Rule = ToTerm ("*") | "/" | "+" | "-" };
_expr.Rule = MakePlusRule (_expr, _val_op2, _value);
```

For the four operations, like '1+2*3-4', what I want to get for _expr is:

```
1 + 2 * 3 - 4
```

And what we actually get is this

```
((1 + 2) * 3) - 4
```

How should such code be modified?

**Comment by sebastienros** [comment]
Here is an example:

Define all operators in a rule like this:

https://github.com/OrchardCMS/OrchardCore/blob/b375c7ffc922fbe7271bf0004955852442e9953a/src/OrchardCore.Modules/OrchardCore.Queries/Sql/SqlGrammar.cs#L149-L153

Then their priority:

https://github.com/OrchardCMS/OrchardCore/blob/b375c7ffc922fbe7271bf0004955852442e9953a/src/OrchardCore.Modules/OrchardCore.Queries/Sql/SqlGrammar.cs#L162-L169

**Comment by fawdlstty** [comment]
This method does not work for me, I still can not control the priority, I hope to find out all in a parallel way, and then handle manually

**Comment by rivantsov** [comment]
but that (operation priority) is the only way to let parser know that you prefer multiplication * done first, even if addition is before it. That's standard way it works in math and in parsers. Why it does not work for you? in what sense it does not work?

**Comment by fawdlstty** [comment]
After I specify the priority, it still resolves in order, such as:

```
((1 + 2) * 3) - 4
1 + (2 * (3 - 4))
```

**Comment by rivantsov** [comment]
what are these 2 lines, why 2? 
it would help if you share the grammar if you can, maybe somewhere in gist

**Comment by fawdlstty** [comment]
```csharp
var _int_val = new RegexBasedTerminal ("int_val", "[\\+\\-]?[0-9]+");
var _expr = new NonTerminal ("expr");
var _value = new NonTerminal ("value") { Rule = _int_val | _expr };
var _op2 = new NonTerminal ("op2") { Rule = ToTerm ("+") | "-" | "*" | "/" };
_expr.Rule = (_value + _op2 + _value) | ("(" + _expr + ")") | _value;
//
RegisterOperators (10, "-", "+");
RegisterOperators (20, "*", "/");
MarkPunctuation ("(", ")");
RegisterBracePair ("(", ")");
MarkTransient (_expr, _value);
Root = _value;
```

For example, this code used to parse `1*2-5*4+7` will parse to `1 * (2 - (5 * (4 + 7)))`

**Comment by rivantsov** [comment]
I don't understand the last sentence

**Comment by rivantsov** [comment]
btw, did you test it in Grammar Explorer? are there any grammar errors?

**Comment by fawdlstty** [comment]
I specified the priority, so I want the parsing to be: `((1 * 2) - (5 * 4)) + 7`

The syntax is correct, otherwise it will not compile, but the priority setting is confusing

**Comment by fawdlstty** [comment]
Grammar Explorer means <https://github.com/daxnet/irony-explorer> project?
It looked like it was easier to see the tree, but that didn't help me

**Comment by rivantsov** [comment]
no, part of Irony sources, there's app GrammarExplorer, to debug grammars

**Comment by rivantsov** [comment]
I tried it in GE, you have whole bunch of grammar construction errors, pls fix these first

**Comment by fawdlstty** [comment]
Thank you very much. I found a way to deal with the problem
