### ISSUE TITLE
Feasibility of complex expression

### ISSUE THREAD

**Issue by rajeshrinayak** [ironyproject/irony#5]
If we give any complex expression like below then irony library will support ??
e.g. "Delta(Abs(Average(x+10)))"

Here Delta, Abs and Average are the functions. So if we have the expression like one function inside another function then how grammar should be for this kind of expression.

Thanks,
Rajeshri

**Comment by yallie** [comment]
Sure, have a look at the [expression evaluator sample](https://github.com/IronyProject/Irony/tree/master/Irony.Interpreter/_Evaluator).
But Irony isn't an expression evaluator, it's a library for implementing your own compilers/interpreters.

Not sure about your use case, but perhaps a simple expression evaluator library may fit better?
There are plenty of them, just google for "C# expression evaluator".
