### ISSUE TITLE
Irony.dll shows 1.1 for 1.2 download.

### ISSUE THREAD

**Issue by crokusek** [ironyproject/irony#57]
I downloaded the 1.2 version but the .Irony.dll itself indicates that it is 1.1 (FileExplorer -> Properties -> Details tab).

This may be coming from AssemblyInfo.cs file which does indicate 1.1

Thanks in advance for looking into this.

**Comment by rivantsov** [comment]
thanks for the info. yeah, I was not very accurate at the time with details like this. Will make it better if I get the time in the future to refresh the framework

**Comment by rivantsov** [comment]
Fixed in 1.5.3
