### ISSUE TITLE
peverify-compat removed leads to VerificationException

### ISSUE THREAD

**Issue by MartinMedMitten** [ironyproject/irony#65]
Since upgrading to 1.5.0 i get System.Security.VerificationException : Operation could destabilize the runtime.
   at Irony.Parsing.ParsingContext.ComputeStackRangeSpan(Int32 nodeCount)

This [commit](https://github.com/IronyProject/Irony/pull/59/commits/cdfd2973c3ba32802608d8157fced810bad955e5) removed `<Features>peverify-compat</Features>` from 010.irony.csproj 

I tried rebuilding Irony locally with peverify-compat and that seemed to fix the problem, but i'm very uncertain if there are any problems with adding it back.

**Comment by rivantsov** [comment]
thank you for finding and investigating it, will look at it and fix it

**Comment by rivantsov** [comment]
added \<Features\> back. Looks like this stuff is relevant only for pre .net core stuff, full fx. man, time to move on! -)
