### ISSUE TITLE
Parsing in .NET (Core) is significantly slower compared to .NET Framework

### ISSUE THREAD

**Issue by davidnemeti** [ironyproject/irony#70]
Parsing using **English** or **Invariant** culture in .NET (Core) is **5x slower** compared to .NET Framework.

Parsing using **non-English** culture in .NET (Core) is **11x slower** compared to .NET Framework.

> [!NOTE]
> This is because the **`string.IndexOf`** method has a massive performance regression in .NET (Core) since they use [ICU](https://icu.unicode.org/) instead of [NLS](https://learn.microsoft.com/en-us/windows/win32/intl/national-language-support). (On _Unix_ ICU has always been used, but on _Windows_ they switched from NLS to ICU in .NET 5)
> 
> https://github.com/dotnet/runtime/issues/96221
> https://github.com/dotnet/runtime/issues/40942
> https://github.com/dotnet/runtime/issues/37815
> https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

ICU is part of the Windows OneCore base, and while ICU has been updated on Windows 11, it has not been updated on Windows 10. Although, I do not know whether this serious performance problem has been fixed in the latest ICU version. Nevertheless, the performance might vary between different platforms.

If I manually **revert back to using NLS** in my project file as a _workaround_, then the performance is as good in .NET (Core) as in .NET Framework:

```csproj
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
</ItemGroup>
```

> [!TIP]
> I tried changing the `string.IndexOf` usages in Irony so they use `StringComparison.Ordinal`, and after the change the performance was as good in .NET (Core) as in .NET Framework. I think this is the _solution_, since - as far as I can see - there is no reason to use the default `string.IndexOf` overload which does not have a `StringComparison` parameter thus being culture specific by using `StringComparison.CurrentCulture` implicitly.

**Comment by rivantsov** [comment]
thanks so much for bringing this up, I will review the PR and other info and merge/rebuild it

**Comment by sebastienros** [comment]
I ran a benchmark locally, which confirms the statements, but also provides another solution.

The test look like this:

```c#
        private const string _helloWorldNoEscape = "Hello World!!!/n";
        
        [Benchmark(Baseline = true), BenchmarkCategory("ROS.IndexOf")]
        public int RosIndexOfChar()
        {
            return _helloWorldNoEscape.AsSpan().IndexOf('\\');
        }
```

I varied between `ReadOnlySpan<char>.IndexOf` and `string.IndexOf`, and also with `char` and `string` as an argument.

I believe `ROS.IndexOf(string)` is actually not using ICU either (it's converting the string to ROS implicitly). And it's faster than `string.IndexOf(string, Ordinal)`.

```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.22631.4037/23H2/2023Update/SunValley3)
12th Gen Intel Core i7-1260P, 1 CPU, 16 logical and 12 physical cores
.NET SDK 9.0.100-preview.7.24407.12
  [Host]   : .NET 8.0.8 (8.0.824.36612), X64 RyuJIT AVX2
  ShortRun : .NET 8.0.8 (8.0.824.36612), X64 RyuJIT AVX2

Job=ShortRun  IterationCount=3  LaunchCount=1
WarmupCount=3

| Method                     | Mean      | Error     | StdDev    | Ratio | RatioSD | Allocated | Alloc Ratio |
|--------------------------- |----------:|----------:|----------:|------:|--------:|----------:|------------:|
| RosIndexOfChar             |  1.427 ns | 0.2525 ns | 0.0138 ns |  1.00 |    0.01 |         - |          NA |
| RosIndexOfString           |  2.720 ns | 0.7143 ns | 0.0392 ns |  1.91 |    0.03 |         - |          NA |
| RosIndexOfStringOrdinal    |  2.860 ns | 1.3014 ns | 0.0713 ns |  2.00 |    0.05 |         - |          NA |
|                            |           |           |           |       |         |           |             |
| StringIndexOfChar          |  1.500 ns | 1.4386 ns | 0.0789 ns |  1.00 |    0.06 |         - |          NA |
| StringIndexOfString        | 20.854 ns | 6.4076 ns | 0.3512 ns | 13.92 |    0.65 |         - |          NA |
| StringIndexOfStringOrdinal |  3.890 ns | 1.6617 ns | 0.0911 ns |  2.60 |    0.13 |         - |          NA |
```

**Comment by rivantsov** [comment]
closed by accident, when PR merged, reopening until nuget package updated - soon

**Comment by rivantsov** [comment]
merged, pushed v 1.5.2 to nuget.org
thanks all!

**Comment by davidnemeti** [comment]
@sebastienros indeed, the `int IndexOf<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> value)` function is fast, because it basically uses `StringComparison.Ordinal`. (And I think it is faster than the `string` variant because the `string` variant has a lot more checks.)

However, using the `span` variants has the following problems:
- Using `span` would require to use the [System.Memory](https://www.nuget.org/packages/System.Memory/) nuget package to support .NET Framework. It might not be a problem, but it would be an **extra dependency**, and Irony currently has zero dependency, so one dependency would be a huge difference.
- The `span` variants of `IndexOf` **misses the overloads** with the `startIndex` parameter which are being actively used in Irony.

Regarding the performance: I believe that using the `span` variant (2.7 ns) instead of the `string` (3.8 ns) variant might not be significant at the level of the whole parsing procedure, despite the `span` variant execution time is only 70% of the `string` variant execution time. Although, due to the missing `startIndex` overloads I could not test the `span` variant on my large file, but using some benchmark results we can calculate an estimate on the expected performance benefit.

I ran my **micro** benchmarks for `IndexOf` so that the search substring is found at the 80th character, and I searched for a one-character substring (as far as I know, Irony searches for end symbols which are typically one-character long). The InvariantCulture **search** was 14x slower, while the CurrentCultureHungarian **search** was 414x slower than the Ordinal **search**.

I ran my **macro** benchmarks for the whole parsing procedure on a file which had 3.5 million characters and 95000 lines. The InvariantCulture **parse** was 5x slower, while the CurrentCultureHungarian **parse** was 11x slower than the Ordinal **parse**.

Now we try to calculate the performance benefit for the whole parsing procedure. Let's "1" denote the time of the whole parsing (using the `string` variant with Ordinal for `IndexOf`) as a baseline, since we only interested in ratios. Let's use the numbers from the CurrentCultureHungarian measurements ($r$ is ratio, $t$ is duration):

| `IndexOf` variant | Equation for the durations |
| --- | --- |
| `string` + `Ordinal` | $t_{IndexOf} + t_{other} = 1$ |
| slow | $r_{IndexOf_{slow}} \cdot t_{IndexOf} + t_{other} = r_{whole_{slow}}$ |

The above is a **system of two linear equations** with two **variables** ($t_{IndexOf}$ and $t_{other}$) and two **free parameters** ($r_{IndexOf_{slow}}$ and $r_{whole_{slow}}$).

We want to **calculate** $r_{whole_{span}}$:
```math
\begin{aligned}
r_{whole_{span}} &= r_{IndexOf_{span}} \cdot t_{IndexOf} + t_{other} \\
&= r_{IndexOf_{span}} \cdot t_{IndexOf} + 1 - t_{IndexOf} \\
&= t_{IndexOf} \cdot \left(r_{IndexOf_{span}} - 1\right) + 1 \\
&=  \frac{r_{whole_{slow}} - 1}{r_{IndexOf_{slow}} - 1} \cdot \left(r_{IndexOf_{span}} - 1\right) + 1 \\
&= \left(r_{whole_{slow}} - 1\right) \cdot \frac{r_{IndexOf_{span}} - 1}{r_{IndexOf_{slow}} - 1} + 1
\end{aligned}
```

We can use the numbers as **free parameters** from one of the following rows:

| Culture | $r_{IndexOf_{slow}}$ | $r_{whole_{slow}}$ |
| --- | --- | --- |
| CurrentCultureHungarian | 414 | 11 |
| InvariantCulture | 14 | 5 |

Let's use the numbers of the **CurrentCultureHungarian**:

```math
\begin{aligned}
r_{whole_{span}} &= \left(r_{whole_{slow}} - 1\right) \cdot \frac{r_{IndexOf_{span}} - 1}{r_{IndexOf_{slow}} - 1} + 1 \\
&= (11 - 1) \cdot \frac{0.7 - 1}{414 - 1} + 1 \\
&\approx 0.9927
\end{aligned}
```

If we use the numbers of the **InvariantCulture**, we get a better ratio:
```math
\begin{aligned}
r_{whole_{span}} &= (5 - 1) \cdot \frac{0.7 - 1}{14 - 1} + 1 \\
&\approx 0.9077
\end{aligned}
```

BTW, it is very strange and unfortunate that the default behavior (when there is no explicit `comparisonType` parameter) differs for the `string` (`StringComparison.CurrentCulture`) and for the `span` (`StringComparison.Ordinal`) variants of the `IndexOf` method group. Moreover, for the `string` variant the behavior even differs depending on the value parameter being `string` (`StringComparison.CurrentCulture`) or `char` (`StringComparison.Ordinal`). It is a total mess IMHO.

I would prefer the `StringComparison.Ordinal` as default behavior, but that is just my opinion.

However, I could imagine that the dotnet team "fixes" this discrepancy in the future so that the default behavior would be `StringComparison.CurrentCulture` for both variants. Thus, I would say that we should be explicit about the `comparisonType` to be `StringComparison.Ordinal` (regardless of using the `string` or the `span` variant), and that is what Microsoft recommends too:

> Use overloads that explicitly specify the string comparison rules for string operations. Typically, this involves calling a method overload that has a parameter of type [StringComparison](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison).
> Use [StringComparison.Ordinal](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison#system-stringcomparison-ordinal) or [StringComparison.OrdinalIgnoreCase](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison#system-stringcomparison-ordinalignorecase) for comparisons as your safe default for culture-agnostic string matching.
> Use comparisons with [StringComparison.Ordinal](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison#system-stringcomparison-ordinal) or [StringComparison.OrdinalIgnoreCase](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison#system-stringcomparison-ordinalignorecase) for better performance.

https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings

**Comment by sebastienros** [comment]
Thanks for this exhaustive explanation. NB, there is no startIndex argument because you can use .Slice(starIndex) before it.

**Comment by davidnemeti** [comment]
@sebastienros, indeed, `.Slice(startIndex)` can be used - thanks for pointing this out! It looks like I forgot about the _gist_ of `span`, namely that it can represent any _slice_. 😃

However, I still miss the `startIndex` overloads from the `span` variant of the `IndexOf` method group, because the `span` variant overloads return the found index **relative to the slice**, not the **whole string**, therefore the following two are not equivalent:

| `IndexOf` variant | found index is **relative** to the beginning of the... |
| --- | --- |
| `text.IndexOf(value, startIndex)` | whole string |
| `text.AsSpan(startIndex).IndexOf(value)` | slice |
| `text.AsSpan(startIndex).IndexOf(value) + startIndex` | whole string |

So, being this "post offsetting" a little bit cumbersome and error-prone, I ended up creating my own `IndexOf` overloads when I tried the performance of Irony using the `span` variant:

```csharp
  public static class SpanExtensions
  {
    public static int IndexOf<T>(this ReadOnlySpan<T> span, T value, int startIndex) where T : IEquatable<T> =>
      span.Slice(startIndex).IndexOf(value) + startIndex;

    public static int IndexOf<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> value, int startIndex) where T : IEquatable<T> =>
      span.Slice(startIndex).IndexOf(value) + startIndex;

    public static int IndexOf(this ReadOnlySpan<char> span, ReadOnlySpan<char> value, int startIndex, StringComparison comparisonType) =>
      span.Slice(startIndex).IndexOf(value, comparisonType) + startIndex;

    public static int IndexOf(this ReadOnlySpan<char> span, string value, int startIndex) =>
      span.IndexOf(value.AsSpan(), startIndex);

    public static int IndexOf(this ReadOnlySpan<char> span, string value, StringComparison comparisonType) =>
      span.IndexOf(value.AsSpan(), comparisonType);

    public static int IndexOf(this ReadOnlySpan<char> span, string value, int startIndex, StringComparison comparisonType) =>
      span.IndexOf(value.AsSpan(), startIndex, comparisonType);
  }
```

Anyway, now I was able to measure the **whole parsing procedure** on my huge file (3.5 million characters and 95000 lines), and it turned out that the performance gain we would get by using the `span` variant of `IndexOf` is **not significant**:

| variant | duration |
| --- | --- |
| `string` | 4.08 s |
| `span` | 4.02 s |

$r_{whole_{span}} \approx 0.985$, so the performance gain is approximately 1.5%
