### ISSUE TITLE
NuGet versions - No Tags or Releases since 1.2.0

### ISSUE THREAD

**Issue by omni-htg** [ironyproject/irony#73]
Hello, team!

First of all, I want to give my biggest appreciation to you all for the project, and for keeping it up-to-date all this time.
Today, I come to ask about the NuGet releases since 1.2.0 (so 1.5.0 onwards) that have not have either Release Notes on NuGet nor tags or releases here in GitHub.
Could it be that they are hidden?

Thank you for your time!

**Comment by rivantsov** [comment]
no, these are not hidden, all late upgrades are just minor fixes for minor issues. Look at commit tree.

**Comment by omni-htg** [comment]
Thank you for the confirmation, @rivantsov, appreciate you taking the time.
With the onset of many supply chain attacks I wanted to be sure it was still coming from you.
Thanks!

**Comment by sebastienros** [comment]
Following up on this I would suggest to implement the publication I personally use for my projects. This is as simple as adding this workflow: https://github.com/sebastienros/fluid/blob/main/.github/workflows/publish.yml

What it does is detect that a tag was created, and if it starts with `v`, e.g. `v1.3.1` it builds the packages, forcing their version to be the one from this tag (we don't need to update the csproj, it contains a static random dev value), and then pushes it to nuget. The key is kept in GH application secrets and can be rotated/updated any time.

Then to do a release we just need to create a new Release in GH, assign it the `vx.y.z` tag and all is automated. We get a GH release, a tag, and automatic deployments. Anyone with the correct permission in GH can then trigger a release without giving up NuGet access.

Furthermore, the same kind of workflow can be created to push on MyGet or CloudSmith to host dev packages for each commit on master. This allows users to test new features and fixes before we decide to push on NuGet. This is adding to `build.yml` we already have: https://github.com/sebastienros/fluid/blob/main/.github/workflows/build.yml#L27-L33

**Comment by rivantsov** [comment]
Hi, @sebastienros, and all
sorry for being late with reply. I would be very interested to implement something like this - auto build of release and push to nuget. Auto-build and push to nuget increases the trust into the package/code - it guarantees that nuget binaries match the sources.
 Go for it, let me know what permissions you need and other stuff. I am actually interested in adding one or two persons with full permissions to build or push to nuget (just in case smth happens)
thank you for your offer
Roman
